version: "3"
services:
  hackairan:
    image: hackairan
    ports:
      - "80:80"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ~/data:/data/db
    ports:
      - "27017:27017"